# Generated by Django 2.1.7 on 2019-03-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Product', unique=True),
        ),
    ]
